// 10 different colors for company logo backgrounds
  import 'package:flutter/material.dart';
import 'package:home_service_app/models/job_model.dart';

final List<Color> logoColors = [
    Color(0xFF4F8EF7), // Blue
    Color(0xFFF76F4F), // Orange
    Color(0xFF4FF7A1), // Green
    Color(0xFFF7E14F), // Yellow
    Color(0xFFB44FF7), // Purple
    Color(0xFFF74F8E), // Pink
    Color(0xFF4FF0F7), // Cyan
    Color(0xFF7DF74F), // Lime
    Color(0xFFF79C4F), // Amber
    Color(0xFF4F5AF7), // Indigo
  ];
  // 30 different sample job posts
  final List<JobModel> sampleJobs = [
    JobModel(
      id: 1,
      title: 'Software Engineer',
      description:
          'Develop and maintain web applications using modern frameworks.',
      companyName: 'Tech Innovators',
      companyLocation: 'Addis Ababa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$2,500',
      postedDate: '2025-07-01',
      companyLogo: null,
      category: 'IT',
    ),
    JobModel(
      id: 2,
      title: 'UI/UX Designer',
      description:
          'Design user interfaces and improve user experience for mobile apps.',
      companyName: 'Creative Minds',
      companyLocation: 'Adama',
      jobLocation: 'Hybrid',
      jobType: 'Part-time',
      salary: '\$1,800',
      postedDate: '2025-07-02',
      companyLogo: null,
      category: 'Design',
    ),
    JobModel(
      id: 3,
      title: 'Marketing Specialist',
      description: 'Plan and execute marketing campaigns for new products.',
      companyName: 'MarketGurus',
      companyLocation: 'Bahir Dar',
      jobLocation: 'On-site',
      jobType: 'Full-time',
      salary: '\$2,000',
      postedDate: '2025-07-03',
      companyLogo: null,
      category: 'Marketing',
    ),
    JobModel(
      id: 4,
      title: 'Accountant',
      description: 'Manage company finances and prepare financial reports.',
      companyName: 'FinancePro',
      companyLocation: 'Hawassa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$2,200',
      postedDate: '2025-07-04',
      companyLogo: null,
      category: 'Finance',
    ),
    JobModel(
      id: 5,
      title: 'Sales Executive',
      description: 'Drive sales and build relationships with clients.',
      companyName: 'SalesForce',
      companyLocation: 'Dire Dawa',
      jobLocation: 'Hybrid',
      jobType: 'Part-time',
      salary: '\$1,700',
      postedDate: '2025-07-05',
      companyLogo: null,
      category: 'Sales',
    ),
    JobModel(
      id: 6,
      title: 'Mobile App Developer',
      description: 'Develop mobile applications for Android and iOS.',
      companyName: 'AppWorks',
      companyLocation: 'Addis Ababa',
      jobLocation: 'On-site',
      jobType: 'Full-time',
      salary: '\$2,800',
      postedDate: '2025-07-06',
      companyLogo: null,
      category: 'IT',
    ),
    JobModel(
      id: 7,
      title: 'Project Manager',
      description: 'Lead project teams and ensure timely delivery.',
      companyName: 'PM Solutions',
      companyLocation: 'Mekelle',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$3,000',
      postedDate: '2025-07-07',
      companyLogo: null,
      category: 'Management',
    ),
    JobModel(
      id: 8,
      title: 'Customer Support',
      description: 'Provide support to customers via phone and email.',
      companyName: 'SupportHub',
      companyLocation: 'Gondar',
      jobLocation: 'Hybrid',
      jobType: 'Part-time',
      salary: '\$1,200',
      postedDate: '2025-07-08',
      companyLogo: null,
      category: 'Support',
    ),
    JobModel(
      id: 9,
      title: 'Network Engineer',
      description: 'Maintain and troubleshoot network infrastructure.',
      companyName: 'NetSecure',
      companyLocation: 'Addis Ababa',
      jobLocation: 'On-site',
      jobType: 'Full-time',
      salary: '\$2,600',
      postedDate: '2025-07-09',
      companyLogo: null,
      category: 'IT',
    ),
    JobModel(
      id: 10,
      title: 'Content Writer',
      description: 'Write and edit content for blogs and websites.',
      companyName: 'WriteRight',
      companyLocation: 'Adama',
      jobLocation: 'Remote',
      jobType: 'Part-time',
      salary: '\$1,500',
      postedDate: '2025-07-10',
      companyLogo: null,
      category: 'Writing',
    ),
    JobModel(
      id: 11,
      title: 'HR Manager',
      description: 'Oversee recruitment and employee relations.',
      companyName: 'PeopleFirst',
      companyLocation: 'Hawassa',
      jobLocation: 'Hybrid',
      jobType: 'Full-time',
      salary: '\$2,700',
      postedDate: '2025-07-11',
      companyLogo: null,
      category: 'HR',
    ),
    JobModel(
      id: 12,
      title: 'Graphic Designer',
      description: 'Create graphics and visual assets for marketing.',
      companyName: 'DesignLab',
      companyLocation: 'Bahir Dar',
      jobLocation: 'On-site',
      jobType: 'Part-time',
      salary: '\$1,600',
      postedDate: '2025-07-12',
      companyLogo: null,
      category: 'Design',
    ),
    JobModel(
      id: 13,
      title: 'Operations Coordinator',
      description: 'Coordinate daily operations and logistics.',
      companyName: 'LogistiX',
      companyLocation: 'Addis Ababa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$2,300',
      postedDate: '2025-07-13',
      companyLogo: null,
      category: 'Logistics',
    ),
    JobModel(
      id: 14,
      title: 'Business Analyst',
      description: 'Analyze business processes and recommend improvements.',
      companyName: 'BizInsight',
      companyLocation: 'Dire Dawa',
      jobLocation: 'Hybrid',
      jobType: 'Full-time',
      salary: '\$2,900',
      postedDate: '2025-07-14',
      companyLogo: null,
      category: 'Business',
    ),
    JobModel(
      id: 15,
      title: 'Teacher',
      description: 'Teach mathematics to high school students.',
      companyName: 'Bright Future School',
      companyLocation: 'Adama',
      jobLocation: 'On-site',
      jobType: 'Part-time',
      salary: '\$1,400',
      postedDate: '2025-07-15',
      companyLogo: null,
      category: 'Education',
    ),
    JobModel(
      id: 16,
      title: 'Data Scientist',
      description: 'Analyze data and build predictive models.',
      companyName: 'DataWiz',
      companyLocation: 'Addis Ababa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$3,200',
      postedDate: '2025-07-16',
      companyLogo: null,
      category: 'IT',
    ),
    JobModel(
      id: 17,
      title: 'Receptionist',
      description: 'Greet visitors and manage front desk operations.',
      companyName: 'Hotel Comfort',
      companyLocation: 'Hawassa',
      jobLocation: 'Hybrid',
      jobType: 'Part-time',
      salary: '\$1,100',
      postedDate: '2025-07-17',
      companyLogo: null,
      category: 'Hospitality',
    ),
    JobModel(
      id: 18,
      title: 'Electrician',
      description: 'Install and repair electrical systems.',
      companyName: 'PowerTech',
      companyLocation: 'Bahir Dar',
      jobLocation: 'On-site',
      jobType: 'Full-time',
      salary: '\$2,000',
      postedDate: '2025-07-18',
      companyLogo: null,
      category: 'Skilled Labor',
    ),
    JobModel(
      id: 19,
      title: 'Chef',
      description: 'Prepare meals and manage kitchen staff.',
      companyName: 'Gourmet Kitchen',
      companyLocation: 'Addis Ababa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$2,400',
      postedDate: '2025-07-19',
      companyLogo: null,
      category: 'Hospitality',
    ),
    JobModel(
      id: 20,
      title: 'Security Guard',
      description: 'Ensure safety and security of premises.',
      companyName: 'SafeZone',
      companyLocation: 'Dire Dawa',
      jobLocation: 'Hybrid',
      jobType: 'Part-time',
      salary: '\$1,000',
      postedDate: '2025-07-20',
      companyLogo: null,
      category: 'Security',
    ),
    JobModel(
      id: 21,
      title: 'Pharmacist',
      description: 'Dispense medications and counsel patients.',
      companyName: 'HealthPlus',
      companyLocation: 'Adama',
      jobLocation: 'On-site',
      jobType: 'Full-time',
      salary: '\$2,500',
      postedDate: '2025-07-21',
      companyLogo: null,
      category: 'Healthcare',
    ),
    JobModel(
      id: 22,
      title: 'Plumber',
      description: 'Install and repair plumbing systems.',
      companyName: 'PipeMasters',
      companyLocation: 'Hawassa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$2,100',
      postedDate: '2025-07-22',
      companyLogo: null,
      category: 'Skilled Labor',
    ),
    JobModel(
      id: 23,
      title: 'Translator',
      description: 'Translate documents and interpret conversations.',
      companyName: 'LinguaLink',
      companyLocation: 'Addis Ababa',
      jobLocation: 'Hybrid',
      jobType: 'Part-time',
      salary: '\$1,900',
      postedDate: '2025-07-23',
      companyLogo: null,
      category: 'Language',
    ),
    JobModel(
      id: 24,
      title: 'Barista',
      description: 'Prepare coffee and serve customers.',
      companyName: 'Coffee Corner',
      companyLocation: 'Bahir Dar',
      jobLocation: 'On-site',
      jobType: 'Part-time',
      salary: '\$1,050',
      postedDate: '2025-07-24',
      companyLogo: null,
      category: 'Hospitality',
    ),
    JobModel(
      id: 25,
      title: 'Logistics Manager',
      description: 'Oversee supply chain and logistics operations.',
      companyName: 'MoveIt',
      companyLocation: 'Addis Ababa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$3,100',
      postedDate: '2025-07-25',
      companyLogo: null,
      category: 'Logistics',
    ),
    JobModel(
      id: 26,
      title: 'Dentist',
      description: 'Provide dental care and treatment to patients.',
      companyName: 'Smile Dental',
      companyLocation: 'Dire Dawa',
      jobLocation: 'Hybrid',
      jobType: 'Full-time',
      salary: '\$3,000',
      postedDate: '2025-07-26',
      companyLogo: null,
      category: 'Healthcare',
    ),
    JobModel(
      id: 27,
      title: 'Photographer',
      description: 'Capture and edit photos for events and clients.',
      companyName: 'PhotoPro',
      companyLocation: 'Adama',
      jobLocation: 'On-site',
      jobType: 'Part-time',
      salary: '\$1,300',
      postedDate: '2025-07-27',
      companyLogo: null,
      category: 'Media',
    ),
    JobModel(
      id: 28,
      title: 'Fitness Trainer',
      description: 'Coach clients and develop fitness plans.',
      companyName: 'FitLife',
      companyLocation: 'Hawassa',
      jobLocation: 'Remote',
      jobType: 'Full-time',
      salary: '\$2,200',
      postedDate: '2025-07-28',
      companyLogo: null,
      category: 'Fitness',
    ),
    JobModel(
      id: 29,
      title: 'Legal Advisor',
      description: 'Provide legal advice and draft documents.',
      companyName: 'LawAssist',
      companyLocation: 'Addis Ababa',
      jobLocation: 'Hybrid',
      jobType: 'Full-time',
      salary: '\$3,400',
      postedDate: '2025-07-29',
      companyLogo: null,
      category: 'Legal',
    ),
    JobModel(
      id: 30,
      title: 'Event Planner',
      description: 'Organize and coordinate events and conferences.',
      companyName: 'Eventive',
      companyLocation: 'Bahir Dar',
      jobLocation: 'On-site',
      jobType: 'Part-time',
      salary: '\$1,750',
      postedDate: '2025-07-30',
      companyLogo: null,
      category: 'Events',
    ),
  ];
