// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMhW1NSqGLnLUWcNHfrll9LWa6CnINmk',
    appId: '1:550887223281:android:d3747a268795f7db93de50',
    messagingSenderId: '550887223281',
    projectId: 'home-service-92c52',
    storageBucket: 'home-service-92c52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-xTKKgM20GOu14UvArfSCe1C7ZgFb4jI',
    appId: '1:550887223281:ios:e9b7cb6ecc3e084493de50',
    messagingSenderId: '550887223281',
    projectId: 'home-service-92c52',
    storageBucket: 'home-service-92c52.firebasestorage.app',
    iosClientId: '550887223281-a6eqcf38ncdtc3vjlopna0einvh2f1if.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeServiceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD1kXO44hQ4RP3068xd4Q9lEsgXWTiNUM',
    appId: '1:550887223281:web:70ad4c0db2705ec893de50',
    messagingSenderId: '550887223281',
    projectId: 'home-service-92c52',
    authDomain: 'home-service-92c52.firebaseapp.com',
    storageBucket: 'home-service-92c52.firebasestorage.app',
    measurementId: 'G-RMS5D6KQZV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-xTKKgM20GOu14UvArfSCe1C7ZgFb4jI',
    appId: '1:550887223281:ios:e9b7cb6ecc3e084493de50',
    messagingSenderId: '550887223281',
    projectId: 'home-service-92c52',
    storageBucket: 'home-service-92c52.firebasestorage.app',
    iosClientId: '550887223281-a6eqcf38ncdtc3vjlopna0einvh2f1if.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD1kXO44hQ4RP3068xd4Q9lEsgXWTiNUM',
    appId: '1:550887223281:web:2755e5e230aec2c493de50',
    messagingSenderId: '550887223281',
    projectId: 'home-service-92c52',
    authDomain: 'home-service-92c52.firebaseapp.com',
    storageBucket: 'home-service-92c52.firebasestorage.app',
    measurementId: 'G-5ZVW4L0FQJ',
  );

}